<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <?php echo $this->tag->getTitle(); ?>
    <?php 	$js = glob("static/js/main.*.js");
    $css = glob("static/css/main.*.css");
    ?>

    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
    <link rel="manifest" href="static/css/manifest.json">
    <link href="/<?=$css[0]?>" rel="stylesheet">
    <?/*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>*/?>

</head>
<body>
<?php echo $this->getContent(); ?>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

<!-- Latest compiled and minified JavaScript -->
<script type="text/javascript" src="/<?=$js[0]?>"></script>

</body>
</html>
