version: '2'

services:
  mysql:
    restart: always
    image: mysql:5.7
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/docker-entrypoint-initdb.d/dump.sql
      - mysql:/var/lib/mysql
      - ./conf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
        - variables.env

  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    ports:
      - "8080:80"
    env_file:
      - variables.env
  app:
    build: docker/app
    restart: always
    working_dir: /project
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/project
      - ./conf/php/cli.ini:/etc/php/7.0/cli/conf.d/99-custom.ini
      - ./conf/php/fpm.ini:/etc/php/7.0/fpm/conf.d/99-custom.ini
    depends_on:
      - mysql
    env_file:
      - variables.env

volumes:

  mysql:
    driver: local

