<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';
require_once __DIR__ . '/../../controllers/Mailer/SendMailer.php';
require_once __DIR__ . '/phpqrcode/qrlib.php';


return ComposerAutoloaderInite214907ee502a6fd496201ba23971a48::getLoader();
